# Generated by Django 5.0.6 on 2024-06-28 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App01", "0002_remove_board_down_remove_board_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
